# Generated by Django 5.0.4 on 2024-04-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userauth_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
