# Generated by Django 5.0.4 on 2024-04-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userauth_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
