# Generated by Django 5.0.4 on 2024-04-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profileuser_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
