# Generated by Django 5.0.4 on 2024-04-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
    ]
